# Generated by Django 6.0.7 on 2026-07-22 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modeling', '0011_alter_standardfield_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='档案名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '已发布'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('schema', models.JSONField(default=list, help_text='创建时从 StandardField 生成的字段结构', verbose_name='字段结构快照')),
                ('schema_version', models.IntegerField(default=1, help_text='每次同步模型变更时递增', verbose_name='Schema 版本号')),
                ('created_by', models.CharField(blank=True, default='', max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='modeling.domain', verbose_name='所属域')),
            ],
            options={
                'verbose_name': '档案配置',
                'verbose_name_plural': '档案配置',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='{field_code: value} 格式的键值对', verbose_name='档案数据')),
                ('status', models.CharField(choices=[('active', '启用'), ('deleted', '已删除')], default='active', max_length=20, verbose_name='状态')),
                ('version', models.IntegerField(default=1, verbose_name='当前版本号')),
                ('sync_status', models.CharField(default='unsynced', help_text='unsynced: 未同步, synced: 已同步, partial: 部分同步, error: 同步失败', max_length=20, verbose_name='同步状态')),
                ('created_by', models.CharField(blank=True, default='', max_length=100, verbose_name='创建人')),
                ('updated_by', models.CharField(blank=True, default='', max_length=100, verbose_name='最后修改人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='archive.archive', verbose_name='所属档案')),
            ],
            options={
                'verbose_name': '档案记录',
                'verbose_name_plural': '档案记录',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('operation_type', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除'), ('rollback', '回滚'), ('pin', '定版'), ('unpin', '取消定版'), ('sync', '同步'), ('schema_sync', '模型同步')], max_length=20, verbose_name='操作类型')),
                ('change_summary', models.JSONField(blank=True, null=True, verbose_name='变更摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='archive.archive', verbose_name='所属档案')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to='archive.archiverecord', verbose_name='所属记录')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveRecordVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('data', models.JSONField(verbose_name='该版本数据快照')),
                ('schema', models.JSONField(blank=True, null=True, verbose_name='该版本 Schema 快照')),
                ('operated_by', models.CharField(max_length=100, verbose_name='操作人')),
                ('operated_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operation_type', models.CharField(choices=[('create', '新增'), ('update', '修改'), ('delete', '删除'), ('rollback', '回滚'), ('pin', '定版'), ('schema_sync', '模型同步')], max_length=20, verbose_name='操作类型')),
                ('change_summary', models.JSONField(blank=True, help_text='{"changed_fields": [{"field":"name","old":"旧值","new":"新值"}]}', null=True, verbose_name='变更摘要')),
                ('is_pinned', models.BooleanField(default=False, help_text='定版后不可修改', verbose_name='已定版')),
                ('pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='定版时间')),
                ('pinned_by', models.CharField(blank=True, default='', max_length=100, verbose_name='定版人')),
                ('pin_note', models.TextField(blank=True, default='', verbose_name='定版说明')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='archive.archiverecord', verbose_name='所属记录')),
            ],
            options={
                'verbose_name': '版本快照',
                'verbose_name_plural': '版本快照',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=100, verbose_name='操作人')),
                ('status', models.CharField(choices=[('pending', '待同步'), ('success', '成功'), ('partial', '部分成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('details', models.JSONField(default=list, verbose_name='同步详情')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='archive.archive', verbose_name='所属档案')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='archive.archiverecord', verbose_name='同步记录')),
            ],
            options={
                'verbose_name': '同步日志',
                'verbose_name_plural': '同步日志',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='archiverecord',
            index=models.Index(fields=['archive', 'status'], name='archive_arc_archive_db6685_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveoperationlog',
            index=models.Index(fields=['archive', '-created_at'], name='archive_arc_archive_673d5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='archiverecordversion',
            unique_together={('record', 'version')},
        ),
    ]
