# Generated by Django 6.0.7 on 2026-07-23 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('path', models.CharField(help_text='如 /api/data/store-master，用于展示', max_length=200, unique=True, verbose_name='接口路径')),
                ('exposed_fields', models.JSONField(blank=True, default=list, help_text='字段 code 列表，空表示全部字段', verbose_name='暴露字段')),
                ('filter_conditions', models.JSONField(blank=True, default=list, verbose_name='筛选条件')),
                ('auth_roles', models.JSONField(blank=True, default=list, verbose_name='角色/部门授权')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=20, verbose_name='状态')),
                ('created_by', models.CharField(blank=True, default='', max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='archive.archive', verbose_name='所属档案')),
            ],
            options={
                'verbose_name': '数据服务API',
                'verbose_name_plural': '数据服务API',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['archive', 'status'], name='archive_arc_archive_e517cb_idx')],
            },
        ),
    ]
