# Generated by Django 6.0.7 on 2026-07-28 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_archiveapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiverecord',
            name='lineage',
            field=models.JSONField(blank=True, default=dict, help_text='每个字段值的来源与更新时间', verbose_name='字段血缘'),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='overrides',
            field=models.JSONField(blank=True, default=dict, help_text='受保护字段同步拉数时不自动覆盖', verbose_name='修正保护标记'),
        ),
        migrations.CreateModel(
            name='ArchiveFieldConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_code', models.CharField(max_length=100, verbose_name='字段代码')),
                ('archive_value', models.JSONField(blank=True, null=True, verbose_name='档案值')),
                ('source_value', models.JSONField(blank=True, null=True, verbose_name='源值')),
                ('source_table', models.CharField(blank=True, default='', max_length=200, verbose_name='源表')),
                ('suggested_action', models.CharField(choices=[('accept_source', '建议接受源值'), ('keep_archive', '建议保留档案值')], default='accept_source', max_length=20, verbose_name='建议裁决')),
                ('is_protected', models.BooleanField(default=False, help_text='该字段存在 override 保护标记', verbose_name='修正保护中')),
                ('status', models.CharField(choices=[('pending', '待审查'), ('resolved_accept', '已裁决-接受源值'), ('resolved_keep', '已裁决-保留档案值'), ('voided', '已作废')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='产生时间')),
                ('resolved_by', models.CharField(blank=True, default='', max_length=100, verbose_name='裁决人')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='裁决时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_conflicts', to='archive.archive', verbose_name='所属档案')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_conflicts', to='archive.archiverecord', verbose_name='所属记录')),
            ],
            options={
                'verbose_name': '字段冲突项',
                'verbose_name_plural': '字段冲突项',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['record', 'field_code', 'status'], name='archive_arc_record__97e774_idx'), models.Index(fields=['archive', 'status'], name='archive_arc_archive_8b7bbe_idx')],
            },
        ),
    ]
