# Generated by Django 6.0.7 on 2026-07-29 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_archiverecord_lineage_archiverecord_overrides_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='archivefieldconflict',
            name='archive_arc_record__97e774_idx',
        ),
        migrations.RemoveIndex(
            model_name='archivefieldconflict',
            name='archive_arc_archive_8b7bbe_idx',
        ),
        migrations.DeleteModel(
            name='ArchiveFieldConflict',
        ),
    ]
