# Generated by Django 6.0.7 on 2026-07-29 02:51

from django.db import migrations, models


def split_layers(apps, schema_editor):
    """存量拆分：按 lineage 来源把 data 拆入 source_data / manual_data 两层。
    计算字段（schema source='computed'）两层都不进，仅留在 data。
    首次刷新后 source_data 会被真实源数据校准，此处近似正确即可。"""
    Archive = apps.get_model('archive', 'Archive')
    ArchiveRecord = apps.get_model('archive', 'ArchiveRecord')
    for archive in Archive.objects.all():
        computed_codes = {item.get('code') for item in (archive.schema or [])
                          if item.get('source') == 'computed'}
        batch = []
        for rec in ArchiveRecord.objects.filter(archive=archive).iterator():
            data = rec.data or {}
            lineage = rec.lineage or {}
            manual, source = {}, {}
            for code, value in data.items():
                if code in computed_codes:
                    continue
                if lineage.get(code, {}).get('source') in ('manual', 'resolve'):
                    manual[code] = value
                else:
                    source[code] = value
            rec.manual_data = manual
            rec.source_data = source
            batch.append(rec)
            if len(batch) >= 500:
                ArchiveRecord.objects.bulk_update(batch, ['source_data', 'manual_data'])
                batch = []
        if batch:
            ArchiveRecord.objects.bulk_update(batch, ['source_data', 'manual_data'])


def merge_layers_back(apps, schema_editor):
    """回滚：data 本就是合并结果，清空两层即可。"""
    ArchiveRecord = apps.get_model('archive', 'ArchiveRecord')
    ArchiveRecord.objects.update(source_data={}, manual_data={})


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_remove_archivefieldconflict_archive_arc_record__97e774_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiverecord',
            name='manual_data',
            field=models.JSONField(blank=True, default=dict, help_text='人工修改的字段值，合并时覆盖底层', verbose_name='人工覆盖层'),
        ),
        migrations.AddField(
            model_name='archiverecord',
            name='source_data',
            field=models.JSONField(blank=True, default=dict, help_text='schema code → 源值，同步时整层替换', verbose_name='源同步底层'),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='data',
            field=models.JSONField(default=dict, help_text='合并物化结果：source_data 为底 + manual_data 覆盖 + 计算字段，{field_code: value}', verbose_name='档案数据'),
        ),
        migrations.RunPython(split_layers, merge_layers_back),
    ]
