# Generated by Django 6.0.7 on 2026-07-29 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_archiverecord_manual_data_archiverecord_source_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveChangeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_source', models.CharField(choices=[('sync', '源侧同步'), ('manual', '档案侧编辑')], max_length=20, verbose_name='变更来源')),
                ('operator', models.CharField(blank=True, default='', max_length=100, verbose_name='操作人')),
                ('stats', models.JSONField(blank=True, default=dict, help_text='{"records_created":0,"records_updated":0,"records_deactivated":0,"records_reactivated":0}', verbose_name='批次统计')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_batches', to='archive.archive', verbose_name='所属档案')),
            ],
            options={
                'verbose_name': '数据变更批次',
                'verbose_name_plural': '数据变更批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveChangeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_key', models.CharField(blank=True, default='', help_text='主键值快照，记录删除后仍可识别', max_length=200, verbose_name='记录标识')),
                ('change_type', models.CharField(choices=[('created', '新增'), ('updated', '修改'), ('deactivated', '停用'), ('reactivated', '复活')], max_length=20, verbose_name='变更类型')),
                ('field_changes', models.JSONField(blank=True, default=list, help_text='[{"field":"code","name":"中文名","old":旧值,"new":新值}]', verbose_name='字段变更')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_details', to='archive.archive', verbose_name='所属档案')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='archive.archivechangebatch', verbose_name='所属批次')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_details', to='archive.archiverecord', verbose_name='所属记录')),
            ],
            options={
                'verbose_name': '数据变更明细',
                'verbose_name_plural': '数据变更明细',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='archivechangebatch',
            index=models.Index(fields=['archive', '-created_at'], name='archive_arc_archive_1b8c21_idx'),
        ),
        migrations.AddIndex(
            model_name='archivechangedetail',
            index=models.Index(fields=['archive', '-created_at'], name='archive_arc_archive_da0837_idx'),
        ),
    ]
