# Generated by Django 6.0.7 on 2026-07-30 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_archivechangebatch_archivechangedetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivechangebatch',
            name='change_source',
            field=models.CharField(choices=[('sync', '源侧同步'), ('manual', '档案侧编辑'), ('consistency', '一致性审核')], max_length=20, verbose_name='变更来源'),
        ),
        migrations.AlterField(
            model_name='archivechangedetail',
            name='change_type',
            field=models.CharField(choices=[('created', '新增'), ('updated', '修改'), ('deactivated', '停用'), ('reactivated', '复活'), ('reviewed', '已审核'), ('ignored', '已忽略')], max_length=20, verbose_name='变更类型'),
        ),
        migrations.CreateModel(
            name='ConsistencyIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_key', models.CharField(help_text='主键值快照', max_length=200, verbose_name='记录标识')),
                ('field_code', models.CharField(max_length=100, verbose_name='字段编码')),
                ('field_name', models.CharField(blank=True, default='', max_length=200, verbose_name='字段名称')),
                ('primary_source', models.CharField(blank=True, default='', help_text='表名.物理列', max_length=200, verbose_name='主字段来源')),
                ('primary_value', models.TextField(blank=True, null=True, verbose_name='主字段值')),
                ('member_source', models.CharField(help_text='表名.物理列', max_length=200, verbose_name='成员来源')),
                ('member_value', models.TextField(blank=True, null=True, verbose_name='成员值')),
                ('status', models.CharField(choices=[('open', '待审核'), ('reviewed', '已审核'), ('ignored', '已忽略'), ('resolved', '已消失')], default='open', max_length=20, verbose_name='状态')),
                ('review_note', models.CharField(blank=True, default='', max_length=500, verbose_name='审核备注')),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=100, verbose_name='审核人')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('first_found_at', models.DateTimeField(auto_now_add=True, verbose_name='首次发现时间')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='最近检查时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_issues', to='archive.archive', verbose_name='所属档案')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consistency_issues', to='archive.archiverecord', verbose_name='所属记录')),
            ],
            options={
                'verbose_name': '一致性差异记录',
                'verbose_name_plural': '一致性差异记录',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['archive', 'status'], name='archive_con_archive_61cba1_idx')],
                'constraints': [models.UniqueConstraint(fields=('archive', 'record_key', 'field_code', 'member_source'), name='uniq_consistency_issue_key')],
            },
        ),
    ]
