# Generated by Django 6.0.7 on 2026-07-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_alter_archivechangebatch_change_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivechangedetail',
            name='record_label',
            field=models.CharField(blank=True, default='', help_text='组合字段值快照（变更时点），让用户一眼识别变更的是哪条数据', max_length=500, verbose_name='记录信息'),
        ),
    ]
