# Generated by Django 6.0.7 on 2026-07-31 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_consistencyissuehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivechangedetail',
            name='change_type',
            field=models.CharField(choices=[('created', '新增'), ('updated', '修改'), ('deactivated', '停用'), ('reactivated', '复活'), ('reviewed', '已审核'), ('ignored', '已忽略'), ('rollback', '回滚')], max_length=20, verbose_name='变更类型'),
        ),
    ]
