# Generated by Django 6.0.7 on 2026-08-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_add_rollback_change_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivechangedetail',
            name='version_after',
            field=models.IntegerField(blank=True, null=True, verbose_name='变更后版本号'),
        ),
        migrations.AddField(
            model_name='archivechangedetail',
            name='version_before',
            field=models.IntegerField(blank=True, null=True, verbose_name='变更前版本号'),
        ),
    ]
