# Generated by Django 6.0.7 on 2026-08-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_add_change_detail_version_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivechangedetail',
            name='change_type',
            field=models.CharField(choices=[('created', '新增'), ('updated', '修改'), ('deactivated', '停用（源侧已删）'), ('reactivated', '复活（源侧恢复）'), ('reviewed', '已审核'), ('ignored', '已忽略'), ('rollback', '回滚')], max_length=20, verbose_name='变更类型'),
        ),
    ]
