# Generated by Django 6.0.7 on 2026-08-04 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_alter_archivechangedetail_change_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsistencyCheckRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('composite_member', '组合字段成员一致性'), ('archive_source_diff', '档案侧与源侧差异'), ('orphan_source_record', '源侧孤立记录'), ('schema_drift', 'Schema 结构漂移')], max_length=30, verbose_name='检查类型')),
                ('field_code', models.CharField(blank=True, default='', max_length=100, verbose_name='字段编码')),
                ('member_source', models.CharField(blank=True, default='', max_length=200, verbose_name='成员来源')),
                ('disabled', models.BooleanField(default=True, verbose_name='已失效')),
                ('disabled_by', models.CharField(blank=True, default='', max_length=100, verbose_name='操作人')),
                ('disabled_at', models.DateTimeField(auto_now_add=True, verbose_name='失效时间')),
                ('disabled_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='失效原因')),
            ],
            options={
                'verbose_name': '一致性检查规则',
                'verbose_name_plural': '一致性检查规则',
                'ordering': ['-disabled_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='consistencyissue',
            name='uniq_consistency_issue_key',
        ),
        migrations.AddField(
            model_name='consistencyissue',
            name='check_rule_key',
            field=models.CharField(blank=True, default='', help_text='标识具体检查规则，如 composite_member:field_code:member_source', max_length=500, verbose_name='规则标识'),
        ),
        migrations.AddField(
            model_name='consistencyissue',
            name='check_type',
            field=models.CharField(choices=[('composite_member', '组合字段成员一致性'), ('archive_source_diff', '档案侧与源侧差异'), ('orphan_source_record', '源侧孤立记录'), ('schema_drift', 'Schema 结构漂移')], default='composite_member', max_length=30, verbose_name='检查类型'),
        ),
        migrations.AddField(
            model_name='consistencyissue',
            name='detail',
            field=models.JSONField(blank=True, default=None, help_text='不同检查类型的额外信息，如 schema_drift 的具体差异、orphan 的主键值等', null=True, verbose_name='补充详情'),
        ),
        migrations.AlterField(
            model_name='consistencyissue',
            name='field_code',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='字段编码'),
        ),
        migrations.AlterField(
            model_name='consistencyissue',
            name='member_source',
            field=models.CharField(blank=True, default='', help_text='表名.物理列', max_length=200, verbose_name='成员来源'),
        ),
        migrations.AddIndex(
            model_name='consistencyissue',
            index=models.Index(fields=['archive', 'check_type'], name='archive_con_archive_7c5d9f_idx'),
        ),
        migrations.AddConstraint(
            model_name='consistencyissue',
            constraint=models.UniqueConstraint(fields=('archive', 'record_key', 'field_code', 'member_source', 'check_type'), name='uniq_consistency_issue_key'),
        ),
        migrations.AddField(
            model_name='consistencycheckrule',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consistency_rules', to='archive.archive', verbose_name='所属档案'),
        ),
        migrations.AddConstraint(
            model_name='consistencycheckrule',
            constraint=models.UniqueConstraint(fields=('archive', 'check_type', 'field_code', 'member_source'), name='uniq_consistency_check_rule'),
        ),
    ]
