# Generated by Django 6.0.7 on 2026-08-05 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_consistencycheckrule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='密钥名称')),
                ('key_prefix', models.CharField(help_text='明文前缀，如 mdm_ab12****，仅展示用', max_length=12, verbose_name='密钥标识')),
                ('key_hash', models.CharField(help_text='SHA-256，明文不落库', max_length=64, unique=True, verbose_name='密钥哈希')),
                ('status', models.CharField(choices=[('active', '启用'), ('revoked', '已吊销')], default='active', max_length=20, verbose_name='状态')),
                ('expires_at', models.DateTimeField(blank=True, help_text='空=永久有效', null=True, verbose_name='过期时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='吊销时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最近调用时间')),
                ('total_calls', models.IntegerField(default=0, verbose_name='累计调用次数')),
                ('created_by', models.CharField(blank=True, default='', max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'API密钥',
                'verbose_name_plural': 'API密钥',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='archiveapi',
            name='allowed_operations',
            field=models.JSONField(blank=True, default=list, help_text='read/create/update/delete 子集，默认 [read]', verbose_name='允许操作'),
        ),
        migrations.AddField(
            model_name='archiveapi',
            name='rate_limit_per_min',
            field=models.IntegerField(default=0, help_text='按密钥维度每分钟调用上限，0=不限', verbose_name='限流（次/分/密钥）'),
        ),
        migrations.AddField(
            model_name='archiveapi',
            name='slug',
            field=models.CharField(blank=True, help_text='对外网关路径段，如 store-master，生成 /api/open/store-master/', max_length=100, null=True, unique=True, verbose_name='对外路径标识'),
        ),
        migrations.AlterField(
            model_name='archivechangebatch',
            name='change_source',
            field=models.CharField(choices=[('sync', '源侧同步'), ('manual', '档案侧编辑'), ('consistency', '一致性审核'), ('api', '外部接口写入')], max_length=20, verbose_name='变更来源'),
        ),
        migrations.CreateModel(
            name='ApiCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(blank=True, default='', max_length=100, verbose_name='密钥名称快照')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=300, verbose_name='请求路径')),
                ('status_code', models.IntegerField(default=0, verbose_name='响应状态码')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('client_ip', models.CharField(blank=True, default='', max_length=64, verbose_name='客户端IP')),
                ('error_summary', models.CharField(blank=True, default='', max_length=200, verbose_name='错误摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='调用时间')),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='archive.archiveapi', verbose_name='调用接口')),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='archive.apikey', verbose_name='调用密钥')),
            ],
            options={
                'verbose_name': 'API调用日志',
                'verbose_name_plural': 'API调用日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='archive_api_created_56fa2f_idx'), models.Index(fields=['api', '-created_at'], name='archive_api_api_id_e1cddc_idx'), models.Index(fields=['api_key', '-created_at'], name='archive_api_api_key_c6882e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApiKeyGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_operations', models.JSONField(default=list, help_text='read/create/update/delete 子集，不得超过 API 自身 allowed_operations', verbose_name='操作范围')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='授权时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_grants', to='archive.archiveapi', verbose_name='授权接口')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='archive.apikey', verbose_name='所属密钥')),
            ],
            options={
                'verbose_name': '密钥授权',
                'verbose_name_plural': '密钥授权',
                'constraints': [models.UniqueConstraint(fields=('api_key', 'api'), name='uniq_api_key_grant')],
            },
        ),
    ]
