# Generated by Django 6.0.7 on 2026-08-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_apikey_archiveapi_allowed_operations_and_more'),
        ('modeling', '0030_fieldmapping_conditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRecordDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_key', models.CharField(blank=True, default='', help_text='行键列（row_key_field）的值，明细行身份', max_length=200, verbose_name='行键值')),
                ('source_data', models.JSONField(blank=True, default=dict, help_text='schema code → 源值，同步时整层替换', verbose_name='源同步底层')),
                ('manual_data', models.JSONField(blank=True, default=dict, help_text='人工修改的字段值，合并时覆盖底层', verbose_name='人工覆盖层')),
                ('data', models.JSONField(blank=True, default=dict, help_text='source_data 为底 + manual_data 覆盖', verbose_name='合并物化结果')),
                ('lineage', models.JSONField(blank=True, default=dict, help_text='每个字段值的来源与更新时间', verbose_name='字段血缘')),
                ('overrides', models.JSONField(blank=True, default=dict, verbose_name='修正保护标记')),
                ('status', models.CharField(choices=[('active', '启用'), ('deleted', '已删除')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('mapping', models.ForeignKey(blank=True, help_text='relation_type=detail 的字段映射；删除后明细保留但来源标记丢失', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='modeling.fieldmapping', verbose_name='来源子表关系')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='archive.archiverecord', verbose_name='所属记录')),
            ],
            options={
                'verbose_name': '档案记录明细',
                'verbose_name_plural': '档案记录明细',
                'ordering': ['row_key'],
                'indexes': [models.Index(fields=['record', 'mapping'], name='archive_arc_record__1b8b60_idx')],
                'unique_together': {('record', 'mapping', 'row_key')},
            },
        ),
    ]
