# Generated by Django 6.0.7 on 2026-08-10 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0015_archiverecorddetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivechangedetail',
            name='detail_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.archiverecorddetail', verbose_name='关联明细行'),
        ),
        migrations.AddField(
            model_name='archivechangedetail',
            name='detail_row_key',
            field=models.CharField(blank=True, default='', help_text='行键值快照，明细行删除后仍可识别', max_length=200, verbose_name='明细行键'),
        ),
        migrations.AlterField(
            model_name='archivechangedetail',
            name='change_type',
            field=models.CharField(choices=[('created', '新增'), ('updated', '修改'), ('deactivated', '停用（源侧已删）'), ('reactivated', '复活（源侧恢复）'), ('reviewed', '已审核'), ('ignored', '已忽略'), ('rollback', '回滚'), ('detail_sync', '明细同步')], max_length=20, verbose_name='变更类型'),
        ),
    ]
