# Generated by Django 6.0.7 on 2026-08-11 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0016_archivechangedetail_detail_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveSchemaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.IntegerField(verbose_name='Schema 版本号')),
                ('schema', models.JSONField(default=list, help_text='创建/同步模型时从 StandardField 生成的完整字段结构', verbose_name='Schema 快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schema_snapshots', to='archive.archive', verbose_name='所属档案')),
            ],
            options={
                'verbose_name': 'Schema 版本快照',
                'verbose_name_plural': 'Schema 版本快照',
                'ordering': ['-schema_version'],
                'unique_together': {('archive', 'schema_version')},
            },
        ),
        migrations.AddField(
            model_name='archiverecordversion',
            name='schema_version_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='archive.archiveschemasnapshot', verbose_name='Schema 版本快照引用'),
        ),
    ]
