# Generated by Django 6.0.7 on 2026-08-05 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modeling', '0026_standardfield_primary_field_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='角色名')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='内置角色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '角色',
                'db_table': 'mdm_auth_role',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, default='', max_length=64, verbose_name='显示名')),
                ('roles', models.ManyToManyField(blank=True, related_name='user_profiles', to='mdm_auth.role', verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户档案',
                'db_table': 'mdm_auth_user_profile',
            },
        ),
        migrations.CreateModel(
            name='RoleFieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_codes', models.JSONField(blank=True, default=list, verbose_name='可见字段 code 列表')),
                ('editable_codes', models.JSONField(blank=True, default=list, verbose_name='可编辑字段 code 列表')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_field_permissions', to='modeling.domain', verbose_name='档案域')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_permissions', to='mdm_auth.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色字段权限',
                'db_table': 'mdm_auth_role_field_permission',
                'constraints': [models.UniqueConstraint(fields=('role', 'domain'), name='uniq_role_domain_field_perm')],
            },
        ),
    ]
