# Generated by Django 6.0.7 on 2026-07-13 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='域名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='域编码')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.CharField(choices=[('active', '启用'), ('deprecated', '已废弃')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '主数据域',
                'verbose_name_plural': '主数据域',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分组名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_groups', to='modeling.domain', verbose_name='所属域')),
            ],
            options={
                'verbose_name': '字段分组',
                'verbose_name_plural': '字段分组',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='表名称')),
                ('code', models.CharField(max_length=50, verbose_name='表编码')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('type', models.CharField(choices=[('local', '本地数据表'), ('source', '数据源表')], default='local', max_length=20, verbose_name='表类型')),
                ('source_config', models.JSONField(blank=True, default=None, help_text='数据源表时配置：{"host":"","port":"","db_name":"","table_name":"","user":"","password":""}', null=True, verbose_name='数据源配置')),
                ('status', models.CharField(choices=[('active', '启用'), ('deprecated', '已废弃')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='modeling.domain', verbose_name='所属域')),
            ],
            options={
                'verbose_name': '实体表',
                'verbose_name_plural': '实体表',
                'ordering': ['-created_at'],
                'unique_together': {('domain', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='字段名称')),
                ('code', models.CharField(max_length=50, verbose_name='字段编码')),
                ('field_type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('date', '日期'), ('boolean', '布尔'), ('enum', '枚举')], default='string', max_length=30, verbose_name='数据类型')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='长度')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
                ('default_value', models.CharField(blank=True, default='', max_length=500, verbose_name='默认值')),
                ('validation_rule', models.JSONField(blank=True, default=None, help_text='{"pattern":"","message":""}', null=True, verbose_name='校验规则')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
                ('status', models.CharField(choices=[('active', '启用'), ('deprecated', '已废弃')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='modeling.fieldgroup', verbose_name='所属分组')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='modeling.table', verbose_name='所属表')),
            ],
            options={
                'verbose_name': '字段定义',
                'verbose_name_plural': '字段定义',
                'ordering': ['group__sort_order', 'sort_order', 'id'],
                'unique_together': {('table', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='选项显示名')),
                ('value', models.CharField(max_length=100, verbose_name='选项值')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='modeling.field', verbose_name='所属字段')),
            ],
            options={
                'verbose_name': '枚举选项',
                'verbose_name_plural': '枚举选项',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('field', 'value')},
            },
        ),
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('source_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='modeling.field', verbose_name='源字段')),
                ('target_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_mappings', to='modeling.field', verbose_name='目标字段')),
                ('source_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='modeling.table', verbose_name='源表')),
                ('target_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_mappings', to='modeling.table', verbose_name='目标表')),
            ],
            options={
                'verbose_name': '字段映射',
                'verbose_name_plural': '字段映射',
                'unique_together': {('source_table', 'source_field', 'target_table', 'target_field')},
            },
        ),
    ]
