# Generated by Django 6.0.7 on 2026-07-13 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='数据源名称')),
                ('db_type', models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL')], default='postgresql', max_length=20, verbose_name='数据库类型')),
                ('host', models.CharField(max_length=200, verbose_name='主机地址')),
                ('port', models.IntegerField(default=5432, verbose_name='端口')),
                ('db_name', models.CharField(max_length=100, verbose_name='数据库名')),
                ('username', models.CharField(blank=True, default='', max_length=100, verbose_name='用户名')),
                ('password', models.CharField(blank=True, default='', max_length=200, verbose_name='密码')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据源配置',
                'verbose_name_plural': '数据源配置',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='table',
            name='external_table_name',
            field=models.CharField(blank=True, default='', help_text='数据源表时，指定外部数据库中的表名', max_length=100, verbose_name='外部表名'),
        ),
        migrations.AlterField(
            model_name='table',
            name='source_config',
            field=models.JSONField(blank=True, default=None, help_text='已废弃，请使用 data_source + external_table_name', null=True, verbose_name='数据源配置(旧)'),
        ),
        migrations.AddField(
            model_name='table',
            name='data_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='modeling.datasource', verbose_name='关联数据源'),
        ),
    ]
