# Generated by Django 6.0.7 on 2026-07-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0002_datasource_table_external_table_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='字段注释'),
        ),
        migrations.AddField(
            model_name='field',
            name='semantic_note',
            field=models.CharField(blank=True, default='', help_text='同义词/歧义等语义识别说明', max_length=500, verbose_name='语义标识'),
        ),
    ]
