# Generated by Django 6.0.7 on 2026-07-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0003_field_comment_field_semantic_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='date_format',
            field=models.CharField(blank=True, default='', help_text='日期类型的格式，如 YYYY-MM-DD、YYYY/MM/DD、YYYY-MM-DD HH:mm:ss', max_length=50, verbose_name='日期格式'),
        ),
    ]
