# Generated by Django 6.0.7 on 2026-07-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0006_alter_datasource_db_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='schema',
            field=models.CharField(blank=True, default='', help_text='数据源表时，指定外部数据库中的 schema（如 dbo, public, API 等）', max_length=100, verbose_name='数据库模式'),
        ),
    ]
