# Generated by Django 6.0.7 on 2026-07-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0007_add_schema_to_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_primary_key',
            field=models.BooleanField(default=False, help_text='标记该字段是否为表主键', verbose_name='主键'),
        ),
    ]
