# Generated by Django 6.0.7 on 2026-07-21 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0008_add_is_primary_key_to_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldEquivalenceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_code', models.CharField(help_text='归一化后的字段编码，作为该等价组的标准标识', max_length=100, verbose_name='标准编码')),
                ('standard_name', models.CharField(blank=True, default='', max_length=200, verbose_name='标准中文名')),
                ('note', models.CharField(blank=True, default='', max_length=500, verbose_name='说明')),
                ('source', models.CharField(choices=[('ai', 'AI检测'), ('manual', '手动')], default='ai', max_length=20, verbose_name='来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalence_groups', to='modeling.domain', verbose_name='所属域')),
            ],
            options={
                'verbose_name': '字段等价组',
                'verbose_name_plural': '字段等价组',
                'ordering': ['standard_code', 'id'],
                'unique_together': {('domain', 'standard_code')},
            },
        ),
        migrations.AddField(
            model_name='field',
            name='equivalence_group',
            field=models.ForeignKey(blank=True, help_text='跨表去重后挂靠的标准字段（等价组）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='modeling.fieldequivalencegroup', verbose_name='所属等价组'),
        ),
    ]
