# Generated by Django 6.0.7 on 2026-07-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0010_remove_field_equivalence_group_standardfield_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='standardfield',
            table='modeling_standardfield',
        ),
    ]
