# Generated by Django 6.0.7 on 2026-07-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0011_alter_standardfield_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='标记该域的主表，每个域只能有一个主表。档案数据以主表主键为基准合并其他表数据', verbose_name='主表'),
        ),
    ]
