# Generated by Django 6.0.7 on 2026-07-23 07:40

from django.db import migrations, models
from django.db.models import Q


def preset_etl_excluded(apps, schema_editor):
    """预勾选已知的 ETL/系统审计时间列（如 D_ETL_TIME）为「不同步写回」。
    这些列由源端 ETL 自动维护，不应因其差异被判为「更新」、也不应被回写。"""
    Field = apps.get_model('modeling', 'Field')
    Field.objects.filter(
        Q(code__icontains='ETL_TIME') | Q(code__icontains='ETL_DATE') |
        Q(code__icontains='LOAD_TIME') | Q(code__iexact='D_ETL_TIME')
    ).update(is_sync_excluded=True)


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0012_table_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='is_sync_excluded',
            field=models.BooleanField(default=False, help_text='勾选后：同步到数据源时该字段既不参与差异比对，也不写回（如 ETL 加载时间等系统审计列）', verbose_name='不同步写回')
        ),
        migrations.RunPython(preset_etl_excluded, reverse_noop),
    ]
