# Generated by Django 6.0.7 on 2026-07-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0014_field_release_gates'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardfield',
            name='is_active',
            field=models.BooleanField(default=True, help_text='停用后：该标准字段视为不释放，档案 schema 与记录都不包含它', verbose_name='启用'),
        ),
    ]
