# Generated by Django 6.0.7 on 2026-07-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0015_standardfield_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='distinct_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='去重内容读取时间'),
        ),
        migrations.AddField(
            model_name='field',
            name='distinct_values',
            field=models.JSONField(blank=True, default=None, help_text='该字段去重后的取值样本（上限 100 条），供标准字段匹配与人工识别', null=True, verbose_name='数据去重内容缓存'),
        ),
    ]
