# Generated by Django 6.0.7 on 2026-07-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0016_field_distinct_synced_at_field_distinct_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认AI配置', max_length=100, verbose_name='配置名称')),
                ('api_base', models.CharField(blank=True, default='', help_text='OpenAI 兼容接口的 Base URL，如 https://api.openai.com/v1', max_length=300, verbose_name='接口地址')),
                ('api_key', models.CharField(blank=True, default='', max_length=300, verbose_name='API Key')),
                ('model', models.CharField(blank=True, default='gpt-4o-mini', max_length=100, verbose_name='模型名称')),
                ('temperature', models.FloatField(default=0.2, verbose_name='采样温度')),
                ('timeout', models.IntegerField(default=30, verbose_name='超时时间(秒)')),
                ('enabled', models.BooleanField(default=True, help_text='启用后 ai_service 优先使用此配置；未启用则回退到环境变量', verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI配置',
                'verbose_name_plural': 'AI配置',
                'ordering': ['-updated_at'],
            },
        ),
    ]
