# Generated by Django 6.0.7 on 2026-07-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0017_aiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='prompt_auto_group',
            field=models.TextField(blank=True, default='', verbose_name='字段分组提示词'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='prompt_dedup',
            field=models.TextField(blank=True, default='', verbose_name='跨表去重检测提示词'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='prompt_infer',
            field=models.TextField(blank=True, default='', verbose_name='Excel字段推断提示词'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='prompt_semantic',
            field=models.TextField(blank=True, default='', verbose_name='语义识别提示词'),
        ),
        migrations.AddField(
            model_name='aiconfig',
            name='provider',
            field=models.CharField(blank=True, default='deepseek', help_text='预设厂商（deepseek/openai/qwen/zhipu/moonshot/custom），选定后自动填充接口地址与可选模型', max_length=30, verbose_name='服务厂商'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='api_base',
            field=models.CharField(blank=True, default='https://api.deepseek.com/v1', help_text='OpenAI 兼容接口的 Base URL，如 https://api.deepseek.com/v1', max_length=300, verbose_name='接口地址'),
        ),
        migrations.AlterField(
            model_name='aiconfig',
            name='model',
            field=models.CharField(blank=True, default='deepseek-chat', max_length=100, verbose_name='模型名称'),
        ),
    ]
