# Generated by Django 6.0.7 on 2026-07-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0018_aiconfig_prompt_auto_group_aiconfig_prompt_dedup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='archive_category',
            field=models.CharField(choices=[('unassigned', '未分配'), ('base', '基础字段'), ('calculated', '计算字段')], default='unassigned', help_text='用户手动指定：基础(单表进档案)/计算(占位)/未分配；组合由standard_field外键决定', max_length=20, verbose_name='档案分类'),
        ),
    ]
