# Generated by Django 6.0.7 on 2026-07-25 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0019_field_archive_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardfield',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('discarded', '废弃')], default='active', help_text='废弃后该标准字段进入废弃字段列表', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='ComputedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='字段编码')),
                ('name', models.CharField(max_length=200, verbose_name='字段名称')),
                ('expression', models.TextField(blank=True, default='', help_text='计算表达式（后续实现表达式引擎）', verbose_name='计算表达式')),
                ('release_to_archive', models.BooleanField(default=True, verbose_name='释放到档案')),
                ('status', models.CharField(choices=[('active', '启用'), ('discarded', '废弃')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('depends_on', models.ManyToManyField(blank=True, related_name='computed_dependents', to='modeling.field', verbose_name='依赖字段')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computed_fields', to='modeling.domain', verbose_name='所属域')),
            ],
            options={
                'verbose_name': '计算字段',
                'verbose_name_plural': '计算字段',
                'ordering': ['code', 'id'],
                'unique_together': {('domain', 'code')},
            },
        ),
    ]
