# Generated by Django 6.0.7 on 2026-07-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0020_add_computed_field_and_standard_field_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computedfield',
            options={'ordering': ['execution_order', 'code', 'id'], 'verbose_name': '计算字段', 'verbose_name_plural': '计算字段'},
        ),
        migrations.AddField(
            model_name='computedfield',
            name='depends_on_computed',
            field=models.ManyToManyField(blank=True, related_name='computed_dependents_reverse', to='modeling.computedfield', verbose_name='依赖的计算字段'),
        ),
        migrations.AddField(
            model_name='computedfield',
            name='execution_order',
            field=models.IntegerField(default=0, help_text='DAG拓扑排序位次，batch重算时按此排序', verbose_name='执行顺序'),
        ),
        migrations.AddField(
            model_name='computedfield',
            name='output_type',
            field=models.CharField(choices=[('text', '文本'), ('number', '数字'), ('date', '日期'), ('boolean', '布尔')], default='text', max_length=30, verbose_name='输出类型'),
        ),
        migrations.AddField(
            model_name='computedfield',
            name='parsed_references',
            field=models.JSONField(blank=True, default=list, help_text='[{"table_name":"xxx","field_code":"xxx"}]', verbose_name='解析后的引用列表'),
        ),
        migrations.AlterField(
            model_name='computedfield',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='computed_dependents', to='modeling.field', verbose_name='依赖的物理字段'),
        ),
        migrations.AlterField(
            model_name='computedfield',
            name='expression',
            field=models.TextField(blank=True, default='', help_text='Excel风格公式，如 IF({表名.字段名}="A","是","否")', verbose_name='计算表达式'),
        ),
    ]
