# Generated by Django 6.0.7 on 2026-07-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0021_computed_field_engine_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='modeling.fieldgroup', verbose_name='父分组'),
        ),
    ]
