# Generated by Django 6.0.7 on 2026-07-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0022_add_parent_to_fieldgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='ownership',
            field=models.CharField(choices=[('source', '以源为准'), ('archive', '以我为准')], default='archive', help_text='仅对未归并（solo）物理字段生效：以源为准=档案只读拉取覆盖，以我为准=档案可编辑拉取保护', max_length=20, verbose_name='字段所有权'),
        ),
        migrations.AddField(
            model_name='standardfield',
            name='ownership',
            field=models.CharField(choices=[('source', '以源为准'), ('archive', '以我为准')], default='archive', help_text='以源为准：档案侧只读，拉取时直接覆盖；以我为准：档案可编辑，拉取时保护不覆盖', max_length=20, verbose_name='字段所有权'),
        ),
    ]
