# Generated by Django 6.0.7 on 2026-07-30 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0023_field_ownership_standardfield_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedfield',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computed_fields', to='modeling.fieldgroup', verbose_name='字段分组'),
        ),
    ]
