# Generated by Django 6.0.7 on 2026-07-30 05:36

from django.db import migrations, models


def set_all_ownership_source(apps, schema_editor):
    """存量全刷：默认改为源系统维护，存量 Field/StandardField 一律刷成 source（用户确认）。"""
    Field = apps.get_model('modeling', 'Field')
    StandardField = apps.get_model('modeling', 'StandardField')
    Field.objects.exclude(ownership='source').update(ownership='source')
    StandardField.objects.exclude(ownership='source').update(ownership='source')


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0024_computedfield_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='ownership',
            field=models.CharField(choices=[('source', '源系统维护'), ('archive', '档案维护')], default='source', help_text='仅对未归并（solo）物理字段生效：源系统维护=档案只读拉取覆盖，档案维护=档案可编辑拉取保护', max_length=20, verbose_name='字段维护方'),
        ),
        migrations.AlterField(
            model_name='standardfield',
            name='ownership',
            field=models.CharField(choices=[('source', '源系统维护'), ('archive', '档案维护')], default='source', help_text='源系统维护：档案侧只读，拉取时直接覆盖；档案维护：档案可编辑，拉取时保护不覆盖', max_length=20, verbose_name='字段维护方'),
        ),
        migrations.RunPython(set_all_ownership_source, migrations.RunPython.noop),
    ]
