# Generated by Django 6.0.7 on 2026-07-30 06:20

import django.db.models.deletion
from django.db import migrations, models


def assign_default_primary_fields(apps, schema_editor):
    """存量组合字段默认主字段：取主表成员；无主表成员留空（强制人工设置）。"""
    StandardField = apps.get_model('modeling', 'StandardField')
    for sf in StandardField.objects.all().prefetch_related('members__table'):
        primary_member = None
        for m in sf.members.all():
            if m.status == 'active' and m.table and m.table.is_primary:
                primary_member = m
                break
        if primary_member:
            StandardField.objects.filter(pk=sf.pk).update(
                primary_field=primary_member, primary_field_manual=False)


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0025_alter_field_ownership_alter_standardfield_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardfield',
            name='primary_field',
            field=models.ForeignKey(blank=True, help_text='档案更新的数据源头成员字段；其余成员仅作一致性检查。默认取主表成员，无主表成员时留空强制人工设置', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_standard_fields', to='modeling.field', verbose_name='主字段'),
        ),
        migrations.AddField(
            model_name='standardfield',
            name='primary_field_manual',
            field=models.BooleanField(default=False, help_text='人工指定后主表变更不自动跟随；自动分配的随主表切换', verbose_name='主字段人工指定'),
        ),
        migrations.RunPython(assign_default_primary_fields, migrations.RunPython.noop),
    ]
