# Generated by Django 6.0.7 on 2026-08-08 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0027_configtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='configtable',
            name='data_source',
            field=models.ForeignKey(blank=True, help_text='从哪个数据源同步数据', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_tables', to='modeling.datasource', verbose_name='同步数据源'),
        ),
        migrations.AddField(
            model_name='configtable',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间'),
        ),
        migrations.AddField(
            model_name='configtable',
            name='sync_sql',
            field=models.TextField(blank=True, default='', help_text='SELECT 查询语句，支持 SUBSTRING/DISTINCT 等，结果前两列作为 Key-Value', verbose_name='同步SQL'),
        ),
    ]
