# Generated by Django 6.0.7 on 2026-08-08 07:31

from django.db import migrations, models
from django.db.models import F


def backfill_physical_name(apps, schema_editor):
    """回填 physical_name：所有存量字段的 name 保留了原始列名（改名只改 code 不改 name）"""
    Field = apps.get_model('modeling', 'Field')
    Field.objects.filter(physical_name='').exclude(name='').update(physical_name=F('name'))


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0028_configtable_datasource_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='physical_name',
            field=models.CharField(blank=True, default='', help_text='该字段在外部数据源中的原始列名（改名后保持不变，供同步使用）', max_length=50, verbose_name='物理列名'),
        ),
        migrations.RunPython(backfill_physical_name, migrations.RunPython.noop),
    ]
