# Generated by Django 6.0.7 on 2026-08-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0029_add_physical_name_to_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmapping',
            name='conditions',
            field=models.JSONField(blank=True, default=list, help_text='结构化 ON/WHERE 条件（AND 组合）：[{"field": "物理列名或字段编码", "operator": "eq/ne/gt/ge/lt/le/in", "value": 值}]', verbose_name='筛选条件'),
        ),
        migrations.AddField(
            model_name='fieldmapping',
            name='display_sort_desc',
            field=models.BooleanField(default=True, help_text='True=排序字段降序（最新在前），False=升序', verbose_name='代表行降序'),
        ),
        migrations.AddField(
            model_name='fieldmapping',
            name='display_sort_field',
            field=models.ForeignKey(blank=True, help_text='子表关系：主表展示取代表行的排序字段（如 EFFECTIVE_DATE；同值自动取行键最大，保证确定性）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='modeling.field', verbose_name='代表行排序字段'),
        ),
        migrations.AddField(
            model_name='fieldmapping',
            name='relation_type',
            field=models.CharField(choices=[('reference', '普通关联'), ('detail', '子表关系')], default='reference', help_text='普通关联=属性展开/折叠；子表关系=保留全部行作为明细致子表', max_length=20, verbose_name='关系类型'),
        ),
        migrations.AddField(
            model_name='fieldmapping',
            name='row_key_field',
            field=models.ForeignKey(blank=True, help_text='子表关系：明细行的行身份列（自动检测唯一列，如 ENTRY_ID；检测失败可手动指定）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='modeling.field', verbose_name='明细行键列'),
        ),
    ]
