# Generated by Django 6.0.7 on 2026-08-11 01:52

import django.db.models.deletion
from django.db import migrations, models


def auto_register_detail_configs(apps, schema_editor):
    """存量迁移（2026-08-11 交互改造）：现有 relation_type=detail 映射自动注册子表配置并挂载。
    幂等收敛：get_or_create（已存在则复用）；方向异常的映射（如 27→28）同样注册但由
    detail-check 检测提示方向可疑，不做自动修正。
    """
    FieldMapping = apps.get_model('modeling', 'FieldMapping')
    DetailTableConfig = apps.get_model('modeling', 'DetailTableConfig')
    for fm in FieldMapping.objects.filter(relation_type='detail'):
        cfg, _ = DetailTableConfig.objects.get_or_create(
            domain_id=fm.source_table.domain_id,
            table_id=fm.source_table_id,
            defaults={
                'row_key_field_id': fm.row_key_field_id,
                'display_sort_field_id': fm.display_sort_field_id,
                'display_sort_desc': fm.display_sort_desc,
                'conditions': fm.conditions or [],
            },
        )
        fm.detail_config = cfg
        fm.save(update_fields=['detail_config'])


def unregister_detail_configs(apps, schema_editor):
    """反向：仅解除挂载，不删除注册数据（§8 不删数据）。"""
    FieldMapping = apps.get_model('modeling', 'FieldMapping')
    FieldMapping.objects.filter(relation_type='detail').update(detail_config=None)


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0030_fieldmapping_conditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailTableConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_sort_desc', models.BooleanField(default=True, help_text='True=排序字段降序（最新在前），False=升序', verbose_name='代表行降序')),
                ('conditions', models.JSONField(blank=True, default=list, help_text='结构化 ON/WHERE 条件（AND 组合）：[{"field": "物理列名或字段编码", "operator": "eq/ne/gt/ge/lt/le/in", "value": 值}]', verbose_name='筛选条件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('display_sort_field', models.ForeignKey(blank=True, help_text='主表展示取代表行的排序字段（如 EFFECTIVE_DATE；同值自动取行键最大，保证确定性）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='modeling.field', verbose_name='代表行排序字段')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_configs', to='modeling.domain', verbose_name='所属域')),
                ('row_key_field', models.ForeignKey(blank=True, help_text='明细行的行身份列（自动检测唯一列，如 ENTRY_ID；检测失败可手动指定）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='modeling.field', verbose_name='明细行键列')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_configs', to='modeling.table', verbose_name='明细子表')),
            ],
            options={
                'verbose_name': '明细子表注册',
                'verbose_name_plural': '明细子表注册',
                'ordering': ['-created_at'],
                'unique_together': {('domain', 'table')},
            },
        ),
        migrations.AddField(
            model_name='fieldmapping',
            name='detail_config',
            field=models.ForeignKey(blank=True, help_text='子表关系：挂载到已注册的子表配置（relation_type=detail 时必填）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mappings', to='modeling.detailtableconfig', verbose_name='子表注册配置'),
        ),
        migrations.RunPython(auto_register_detail_configs, unregister_detail_configs),
    ]
