# Generated by Django 6.0.7 on 2026-08-11 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0031_detail_table_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtableconfig',
            name='detail_link_field',
            field=models.ForeignKey(blank=True, help_text='预组合明细表侧关联字段（如 FID），与 header_link_field 配对组成头↔明细关联', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='modeling.field', verbose_name='明细表关联字段'),
        ),
        migrations.AddField(
            model_name='detailtableconfig',
            name='header_link_field',
            field=models.ForeignKey(blank=True, help_text='预组合头表侧关联字段（如 ID），与 detail_link_field 配对组成头↔明细关联', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='modeling.field', verbose_name='头表关联字段'),
        ),
        migrations.AddField(
            model_name='detailtableconfig',
            name='header_table',
            field=models.ForeignKey(blank=True, help_text='预组合头表（如价目表）；与 table（明细表）组合成预组合体，头字段 JOIN 进明细行', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_detail_configs', to='modeling.table', verbose_name='头表'),
        ),
    ]
