# Generated by Django 6.0.7 on 2026-08-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0032_precombine_header_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmapping',
            name='join_type',
            field=models.CharField(choices=[('left', 'LEFT JOIN'), ('inner', 'INNER JOIN')], default='left', help_text='LEFT JOIN=保留无匹配行；INNER JOIN=仅保留匹配行', max_length=10, verbose_name='连接类型'),
        ),
    ]
