# Generated by Django 6.0.7 on 2026-08-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0033_fieldmapping_join_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailtableconfig',
            name='join_type',
            field=models.CharField(choices=[('left', 'LEFT JOIN'), ('inner', 'INNER JOIN')], default='left', help_text='同步时头表与明细表的 JOIN 方式：LEFT=保留无匹配头表的明细行，INNER=仅保留有匹配头表的明细行', max_length=10, verbose_name='JOIN 类型'),
        ),
    ]
